sonar.projectKey=ECI-Maestria_sentinel-health-engine-mobile
sonar.organization=eci-maestria-mobile
sonar.projectName=Sentinel Health

# Solo app (el wearable no tiene tests)
sonar.sources=app/src/main/java
sonar.tests=app/src/test/java

# Binarios compilados (Kotlin + Java)
sonar.java.binaries=app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes,app/build/tmp/kotlin-classes/debug

# Reporte de coverage generado por AGP (enableUnitTestCoverage = true)
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml

sonar.exclusions=**/*Test*.kt,**/R.kt,**/BuildConfig.kt,**/databinding/**,**/room/**/*_Impl.kt
sonar.coverage.exclusions=**/*Test*.kt,**/R.kt,**/BuildConfig.kt
